/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subscription implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long chatid;
    private Long linkid;

    public Subscription() {}

    public Subscription(Subscription value) {
        this.id = value.id;
        this.chatid = value.chatid;
        this.linkid = value.linkid;
    }

    @ConstructorProperties({ "id", "chatid", "linkid" })
    public Subscription(
        @NotNull Long id,
        @Nullable Long chatid,
        @Nullable Long linkid
    ) {
        this.id = id;
        this.chatid = chatid;
        this.linkid = linkid;
    }

    /**
     * Getter for <code>SUBSCRIPTION.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>SUBSCRIPTION.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>SUBSCRIPTION.CHATID</code>.
     */
    @Nullable
    public Long getChatid() {
        return this.chatid;
    }

    /**
     * Setter for <code>SUBSCRIPTION.CHATID</code>.
     */
    public void setChatid(@Nullable Long chatid) {
        this.chatid = chatid;
    }

    /**
     * Getter for <code>SUBSCRIPTION.LINKID</code>.
     */
    @Nullable
    public Long getLinkid() {
        return this.linkid;
    }

    /**
     * Setter for <code>SUBSCRIPTION.LINKID</code>.
     */
    public void setLinkid(@Nullable Long linkid) {
        this.linkid = linkid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Subscription other = (Subscription) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.chatid == null) {
            if (other.chatid != null)
                return false;
        }
        else if (!this.chatid.equals(other.chatid))
            return false;
        if (this.linkid == null) {
            if (other.linkid != null)
                return false;
        }
        else if (!this.linkid.equals(other.linkid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.chatid == null) ? 0 : this.chatid.hashCode());
        result = prime * result + ((this.linkid == null) ? 0 : this.linkid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Subscription (");

        sb.append(id);
        sb.append(", ").append(chatid);
        sb.append(", ").append(linkid);

        sb.append(")");
        return sb.toString();
    }
}
