CREATE TABLE IF NOT EXISTS link (
    id BIGINT PRIMARY KEY NOT NULL,
    url TEXT UNIQUE NOT NULL,
    last_check_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_update_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);