CREATE TABLE IF NOT EXISTS link(
    id BIGINT PRIMARY KEY NOT NULL,
    link TEXT NOT NULL,
    lastCheckTime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    lastUpdateTime TIMESTAMP WITH TIME ZONE DEFAULT now()
);