app:
  test: config
  scheduler:
    interval: 10000

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /openapi/api-docs

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb?useSSL=false
    password: admin
    username: admin


web:
  url:
    base:
      github: https://api.github.com/repos/
      stackoverflow: https://api.stackexchange.com/docs/questions/

server:
  port: 5432

