app:
  test: config
  scheduler:
    interval: 10000
  databaseAccessType: jpa

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /openapi/api-docs

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    password: admin
    username: admin
  liquibase:
    enabled: false


web:
  url:
    base:
      github: https://api.github.com/repos/
      stackoverflow: https://api.stackexchange.com/docs/questions/

server:
  port: 5432

