bot:
  name: tinkBot
  token: ${TOKEN}
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /openapi/api-docs
spring:
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080