bot:
  name: tinkBot
#  token: ${TOKEN}
  token: 5635271809:AAGEH_jME1TMjr3EmsuHaZ_86PeLnjAtzS0
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /openapi/api-docs
spring:
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080