app:
  bot:
    name: tinkBot
    token: ${TOKEN}
  scrapper:
    url: http://localhost:8080
  rabbit-queue:
    exchange-name: updates
    queue-name: updates.queue
    routing-key: upd

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /openapi/api-docs

server:
  port: 8081